export const GLOBAL_CONSTS={
    LOGIN_SUCCESS:"LOGIN_SUCCESS",
    LOGOUT:"LOGOUT",
    SET_TEMP_TOKEN:"SET_TEMP_TOKEN",
    LOADING_START:"LOADING_START",
    LOADING_STOP:"LOADING_STOP",
    LOADING_TOGGLE:"LOADING_TOGGLE",
    ALERT:"ALERT",
    CLOSEMODEL:"CLOSEMODEL",
    MODEL:"MODEL",
}
export const FAMILY_CONSTS={
    ADD_MEMBER:"ADD_MEMBER",
    REMOVE_MEMBER:"REMOVE_MEMBER",
    LOAD_MEMBERS:"LOAD_MEMBERS",
   
}