export const GLOBAL_CONSTS={
    LOGIN_SUCCESS:"LOGIN_SUCCESS",
    LOGOUT:"LOGOUT",
    SET_TEMP_TOKEN:"SET_TEMP_TOKEN",
    LOADING_START:"LOADING_START",
    LOADING_STOP:"LOADING_STOP",
    LOADING_TOGGLE:"LOADING_TOGGLE",
    ALERT:"ALERT",
    CLOSEMODEL:"CLOSEMODEL",
    MODEL:"MODEL",
}